### ISSUE TITLE
mapa-mental

### ISSUE THREAD

**Issue by Evelyn-sj13** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Evelyn-sj13#3]
[Mapa Mental conjuntos y subconjuntos-Evelyn Sosa Jose-1AS.pdf](https://github.com/user-attachments/files/17123054/Mapa.Mental.conjuntos.y.subconjuntos-Evelyn.Sosa.Jose-1AS.pdf)

**Comment by irwingsael** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:4/5
Referencias:5/5
Calificación Final:19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
